/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package com.dt.interpreter;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTLIT = 40;
  /** RegularExpression Id. */
  int POSDIGIT = 41;
  /** RegularExpression Id. */
  int ZERO = 42;
  /** RegularExpression Id. */
  int DIGIT = 43;
  /** RegularExpression Id. */
  int IDENT = 44;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"procedure\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"ref\"",
    "\"{\"",
    "\"}\"",
    "\"=\"",
    "\";\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"print\"",
    "\"var\"",
    "\"for\"",
    "\"in\"",
    "\"case\"",
    "\"of\"",
    "\"[\"",
    "\"]\"",
    "\"->\"",
    "\"cons\"",
    "\"end\"",
    "\"\\\\\"",
    "\"<\"",
    "\"==\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"@\"",
    "\"nonEmpty\"",
    "\"head\"",
    "\"tail\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 38>",
    "<token of kind 39>",
    "<INTLIT>",
    "<POSDIGIT>",
    "\"0\"",
    "<DIGIT>",
    "<IDENT>",
  };

}
