/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package com.dt.interpreter;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTLIT = 29;
  /** RegularExpression Id. */
  int POSDIGIT = 30;
  /** RegularExpression Id. */
  int ZERO = 31;
  /** RegularExpression Id. */
  int DIGIT = 32;
  /** RegularExpression Id. */
  int IDENT = 33;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"procedure\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"ref\"",
    "\"{\"",
    "\"}\"",
    "\"=\"",
    "\";\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"print\"",
    "\"var\"",
    "\"\\\\\"",
    "\"->\"",
    "\"<\"",
    "\"==\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"@\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 27>",
    "<token of kind 28>",
    "<INTLIT>",
    "<POSDIGIT>",
    "\"0\"",
    "<DIGIT>",
    "<IDENT>",
  };

}
